# Generated by Django 6.0.5 on 2026-05-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выгрузки в 1С'),
        ),
        migrations.AddField(
            model_name='order',
            name='exported_to_1c',
            field=models.BooleanField(default=False, verbose_name='Выгружен в 1С'),
        ),
    ]
