# Generated by Django 6.0.5 on 2026-06-04 23:26

from datetime import datetime
from django.db import migrations, models


def migrate_order_data(apps, schema_editor):
    """Переносим данные старых заказов в новые поля и генерируем order_number."""
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        # ФИО из старых first_name / last_name
        full_name = f'{order.first_name} {order.last_name}'.strip()
        order.full_name = full_name or '—'
        # Итог из старого total_price
        order.total = order.total_price or 0
        order.items_total = order.total_price or 0
        # Перенос способов доставки/оплаты (старые коды → новые)
        if order.delivery_type == 'courier':
            order.delivery_method = 'courier'
        elif order.delivery_type == 'transport_company':
            order.delivery_method = 'dl'
        else:
            order.delivery_method = 'pickup'
        if order.payment_type == 'card':
            order.payment_method = 'card'
        elif order.payment_type == 'invoice':
            order.payment_method = 'invoice'
        else:
            order.payment_method = 'on_delivery'
        if order.company:
            order.company_name = order.company
        # Уникальный номер заказа
        year = order.created_at.year if order.created_at else datetime.now().year
        order.order_number = f'К-{year}-{order.pk:05d}'
        order.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('orders', '0003_order_stock_deducted'),
    ]

    operations = [
        # 1. Сначала добавляем новые поля (order_number пока без unique)
        migrations.AddField(
            model_name='order',
            name='buyer_type',
            field=models.CharField(choices=[('fl', 'Физическое лицо'), ('ul', 'Юридическое лицо')], default='fl', max_length=2, verbose_name='Тип покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('cdek', 'СДЭК'), ('dl', 'Деловые Линии'), ('courier', 'Курьер по городу')], default='pickup', max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='order',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_file',
            field=models.CharField(blank=True, max_length=300, verbose_name='Файл счёта'),
        ),
        migrations.AddField(
            model_name='order',
            name='items_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма товаров'),
        ),
        migrations.AddField(
            model_name='order',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картой онлайн'), ('sbp', 'СБП'), ('on_delivery', 'При получении'), ('invoice', 'Безналичный расчёт (счёт)')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сессии'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscribe_news',
            field=models.BooleanField(default=False, verbose_name='Подписка на акции'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),

        # 2. Переносим данные старых заказов в новые поля (пока старые ещё есть)
        migrations.RunPython(migrate_order_data, noop),

        # 3. Теперь, когда order_number у всех уникален, навешиваем unique
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер заказа'),
        ),

        # 4. Удаляем старые поля
        migrations.RemoveField(model_name='order', name='company'),
        migrations.RemoveField(model_name='order', name='delivery_type'),
        migrations.RemoveField(model_name='order', name='first_name'),
        migrations.RemoveField(model_name='order', name='last_name'),
        migrations.RemoveField(model_name='order', name='payment_type'),
        migrations.RemoveField(model_name='order', name='total_price'),
    ]
