# Generated by Django 6.0.5 on 2026-06-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_company_remove_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
    ]
