# Generated by Django 6.0.5 on 2026-05-31 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange1CLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('success', 'Успех'), ('error', 'Ошибка')], max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('count_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано товаров')),
                ('count_created', models.PositiveIntegerField(default=0, verbose_name='Создано новых')),
                ('count_price_updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено цен')),
                ('count_stock_updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено остатков')),
                ('count_no_sku', models.PositiveIntegerField(default=0, verbose_name='Без артикула')),
                ('count_errors', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_text', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('details', models.TextField(blank=True, verbose_name='Детали (JSON)')),
            ],
            options={
                'verbose_name': 'Лог обмена с 1С',
                'verbose_name_plural': 'Логи обмена с 1С',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID товара')),
                ('sku', models.CharField(max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток')),
                ('is_active', models.BooleanField(verbose_name='Активен')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлён')], max_length=20, verbose_name='Действие')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='integration.exchange1clog', verbose_name='Лог импорта')),
            ],
            options={
                'verbose_name': 'Бэкап товара',
                'verbose_name_plural': 'Бэкапы товаров',
            },
        ),
    ]
