# Generated by Django 6.0.5 on 2026-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange1clog',
            name='status',
            field=models.CharField(choices=[('success', 'Успех'), ('error', 'Ошибка'), ('rolled_back', 'Откатан')], max_length=20, verbose_name='Статус'),
        ),
    ]
